# Generated by Django 4.2 on 2023-07-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargepoint', '0003_chargepoint_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('chargepoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargepoint.chargepoint')),
            ],
        ),
    ]
