# Generated by Django 4.2 on 2023-07-31 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat',
            old_name='chargepoint_id',
            new_name='chargepoint',
        ),
    ]
