version: '3.8'

services:
  kafka_zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: kafka_zookeeper
    container_name: kafka_zookeeper
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ov2xmp_ov2xmp-network
  
  kafka:
    image: docker.io/bitnami/kafka:3.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.21.25:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - kafka_zookeeper
    networks:
      - ov2xmp_ov2xmp-network

  mqtt-broker:
    restart: always
    hostname: ov2xmp-mqtt
    container_name: ov2xmp-mqtt
    image: amd64/eclipse-mosquitto
    volumes:
      - "./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
    networks:
      - ov2xmp_ov2xmp-network

  ov2xmp-elasticsearch:
    container_name: ov2xmp-elasticsearch
    hostname: ov2xmp-elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0-amd64
    volumes:
      - "ov2xmp-elasticsearch-data:/usr/share/elasticsearch/data"
      - "./elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    env_file:
      - ./elk/.env-es
    networks:
      - ov2xmp-network

  ov2xmp-elasticsearch-setup:
    container_name: ov2xmp-elasticsearch-setup
    image: ubuntu:latest
    volumes:
      - "./elk/elk-setup.sh:/root/elk-setup.sh"
    command: 'sh -c "apt update && apt install -y curl && chmod 777 /root/elk-setup.sh && /root/elk-setup.sh"'
    env_file:
      - ./elk/.env-es
    networks:
      - ov2xmp-network    
    depends_on:
      - ov2xmp-elasticsearch

  ov2xmp-logstash:
    hostname: ov2xmp-logstash
    container_name: ov2xmp-logstash
    image: docker.elastic.co/logstash/logstash:8.9.0-amd64
    restart: always 
    volumes:
      - "./elk/ov2xmp-normalizer.conf:/usr/share/logstash/config/ov2xmp-normalizer.conf"
    command: bash -c "logstash -f /usr/share/logstash/config/ov2xmp-normalizer.conf --config.reload.automatic"
    env_file:
      - ./elk/.env-logstash
    depends_on:
      - ov2xmp-elasticsearch
    networks:
      - ov2xmp-network

  ov2xmp-kibana:
    hostname: ov2xmp-kibana
    container_name: ov2xmp-kibana
    image: docker.elastic.co/kibana/kibana:8.9.0-amd64
    restart: always  
    env_file:
      - ./elk/.env-kibana
    depends_on:
      - ov2xmp-elasticsearch  
    networks:
      - ov2xmp-network

networks:
  ov2xmp_ov2xmp-network:
    external: true

volumes:
  zookeeper_data:
  kafka_data:
  ov2xmp-elasticsearch-data:
