version: '3.8'

services:
  kafka_zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: kafka_zookeeper
    container_name: kafka_zookeeper
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ov2xmp_ov2xmp-network
  
  kafka:
    image: docker.io/bitnami/kafka:3.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.21.25:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - kafka_zookeeper
    networks:
      - ov2xmp_ov2xmp-network

  mqtt-broker:
    restart: always
    hostname: ov2xmp-mqtt
    container_name: ov2xmp-mqtt
    image: amd64/eclipse-mosquitto
    volumes:
      - "./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
    networks:
      - ov2xmp_ov2xmp-network

networks:
  ov2xmp_ov2xmp-network:
    external: true

volumes:
  zookeeper_data:
  kafka_data: