version: '3.8'
services:
  ov2xmp-redis:
    container_name: ov2xmp-redis
    hostname: ov2xmp-redis
    image: redis:7.2-rc-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis_data:/data
    networks:
      - ov2xmp-network

  ov2xmp-db:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: ov2xmp-db
    hostname: ov2xmp-db
    volumes:
      - ov2xmp_db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env
    networks:
      - ov2xmp-network
 
  ov2xmp-pgadmin4:
    hostname: ov2xmp-pgadmin4
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - '5444:80'
    networks:
      - ov2xmp-network

  ov2xmp-filebrowser:
    image: filebrowser/filebrowser:latest
    ports:
      - 8188:80
    volumes:
      - filebrowser-root:/srv
      - filebrowser-db:/database.db
      - ./docker/filebrowser/filebrowser.json:/.filebrowser.json
    networks:
      - ov2xmp-network
  
  ftp-server:
    image: ev4eu-ftpd:latest
    network_mode: "host"
    volumes:
      - filebrowser-root:/files

  http-file-server:
    image: ev4eu-httpfileserver:latest
    ports:
      - 8881:80
    volumes:
      - filebrowser-root:/files
    networks:
      - ov2xmp-network

  ov2xmp-django:
    container_name: ov2xmp-django
    hostname: ov2xmp-django
    restart: always
    image: gitlab.trsc-ppc.gr:5050/ev4eu/ov2xmp:latest
    volumes:
      - ov2xmp_static_volume:/code/static
      - ov2xmp_media_volume:/code/media
    expose:
      - 8000
      - 9000
    env_file:
      - ./ov2xmp/.env
    depends_on:
      - sdndashboard-db
      - zoo
    networks:
      - ov2xmp-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  ov2xmp-nginx:
    restart: always
    container_name: ov2xmp-nginx
    hostname: ov2xmp-nginx
    image: nginx:stable
    volumes:
      - ov2xmp_static_volume:/code/static
      - ov2xmp_media_volume:/code/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/tls:/etc/nginx/tls
    ports:
      - 8843:443
    networks:
      - ov2xmp-network

  cdr-db:
    image: mongo:4.4.19-rc2
    hostname: cdr-db
    container_name: cdr-db
    ports:
      - 27017:27017     
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ov2xmp_cdr_data:/data/db     
    networks:
      - ov2xmp-network


networks:
  ov2xmp-network:
    driver: bridge


volumes:
  redis_data:
  ov2xmp_db_data:
  filebrowser-db:
  filebrowser-root:
