version: '3.8'
services:
  redis:
    container_name: ov2xmp-redis
    hostname: ov2xmp-redis
    image: redis:7.2-rc-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis_data:/data

  db:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: ov2xmp-db
    hostname: ov2xmp-db
    volumes:
      - ov2xmp_db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env
  
  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - '5444:80'

volumes:
  redis_data:
  ov2xmp_db_data:
