# Generated by Django 4.2 on 2023-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargepoint',
            fields=[
                ('chargepoint_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('chargepoint_model', models.CharField(blank=True, max_length=20)),
                ('chargepoint_vendor', models.CharField(blank=True, max_length=20)),
                ('chargebox_serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('chargepoint_serial_number', models.CharField(blank=True, max_length=25, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(max_length=15)),
                ('websocket_port', models.IntegerField()),
                ('connected', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[('Inoperative', 'Inoperative'), ('Operative', 'Operative')], default='Operative', max_length=11)),
                ('chargepoint_status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], default='Available', max_length=11)),
                ('ocpp_version', models.CharField(choices=[('ocpp16', 'ocpp1.6'), ('ocpp201', 'ocpp2.0.1')], max_length=9)),
                ('last_heartbeat', models.DateTimeField(null=True)),
            ],
        ),
    ]
