# Generated by Django 4.1.7 on 2023-05-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargepoint',
            fields=[
                ('chargepoint_url_identity', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('chargepoint_serial_number', models.CharField(max_length=25)),
                ('chargepoint_model', models.CharField(max_length=20, null=True)),
                ('chargepoint_vendor', models.CharField(max_length=20, null=True)),
                ('ip_address', models.CharField(max_length=15, null=True)),
                ('availability_status', models.IntegerField(choices=[(1, 'Available'), (2, 'Preparing'), (3, 'Charging'), (4, 'Suspended Evse'), (5, 'Suspended Ev'), (6, 'Finishing'), (7, 'Reserved'), (8, 'Unavailable'), (9, 'Faulted')], null=True)),
                ('ocpp_version', models.CharField(max_length=5)),
            ],
        ),
    ]
