# Generated by Django 4.2.1 on 2023-06-21 10:33

from django.db import migrations, models
import ocpp.v16.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargepoint',
            fields=[
                ('chargepoint_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('chargepoint_serial_number', models.CharField(max_length=25, null=True)),
                ('chargepoint_model', models.CharField(max_length=20, null=True)),
                ('chargepoint_vendor', models.CharField(max_length=20, null=True)),
                ('ip_address', models.CharField(max_length=15, null=True)),
                ('connected', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[(ocpp.v16.enums.AvailabilityType['inoperative'], 'Inoperative'), (ocpp.v16.enums.AvailabilityType['operative'], 'Operative')], default=ocpp.v16.enums.AvailabilityType['operative'], max_length=11)),
                ('chargepoint_status', models.CharField(choices=[(ocpp.v16.enums.ChargePointStatus['available'], 'Available'), (ocpp.v16.enums.ChargePointStatus['unavailable'], 'Unavailable'), (ocpp.v16.enums.ChargePointStatus['faulted'], 'Faulted')], default=ocpp.v16.enums.ChargePointStatus['available'], max_length=11)),
                ('ocpp_version', models.CharField(max_length=5)),
                ('last_heartbeat', models.DateTimeField(null=True)),
            ],
        ),
    ]
