# Generated by Django 4.2 on 2023-06-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargepoint',
            name='availability_status',
        ),
    ]
