# Generated by Django 4.2.1 on 2023-06-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='chargebox_serial_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='websocket_port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='chargepoint_model',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='chargepoint_serial_number',
            field=models.CharField(blank=True, default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='chargepoint_vendor',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='ip_address',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='ocpp_version',
            field=models.CharField(choices=[('ocpp16', 'ocpp1.6'), ('ocpp201', 'ocpp2.0.1')], max_length=9),
        ),
    ]
