# Generated by Django 4.2 on 2023-07-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('chargepoint', '0002_remove_chargepoint_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
