# Generated by Django 4.1.7 on 2023-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0002_alter_chargepoint_chargepoint_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepoint',
            name='availability_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
