# Generated by Django 4.2.1 on 2023-06-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0002_chargepoint_chargebox_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepoint',
            name='chargebox_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='chargepoint_serial_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
