# Generated by Django 4.2.1 on 2023-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0003_alter_chargepoint_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='last_heartbeat',
            field=models.DateTimeField(null=True),
        ),
    ]
