# Generated by Django 4.2.1 on 2023-06-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0004_chargepoint_last_heartbeat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargepoint',
            old_name='chargepoint_url_identity',
            new_name='chargepoint_id',
        ),
    ]
