# Generated by Django 4.2.1 on 2023-06-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0005_rename_chargepoint_url_identity_chargepoint_chargepoint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='connected',
            field=models.BooleanField(default=True),
        ),
    ]
