# Generated by Django 4.2.1 on 2023-06-20 21:23

from django.db import migrations, models
import ocpp.v16.enums


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0006_chargepoint_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='chargepoint_status',
            field=models.CharField(choices=[(ocpp.v16.enums.ChargePointStatus['available'], 'Available'), (ocpp.v16.enums.ChargePointStatus['unavailable'], 'Unavailable'), (ocpp.v16.enums.ChargePointStatus['faulted'], 'Faulted')], default=ocpp.v16.enums.ChargePointStatus['available'], max_length=11),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='availability_status',
            field=models.CharField(choices=[(ocpp.v16.enums.AvailabilityType['inoperative'], 'Inoperative'), (ocpp.v16.enums.AvailabilityType['operative'], 'Operative')], default=ocpp.v16.enums.AvailabilityType['operative'], max_length=11),
        ),
    ]
