# Generated by Django 4.2 on 2023-06-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('reservation_id', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.connector')),
            ],
        ),
    ]
