# Generated by Django 4.2.1 on 2023-06-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargepoint', '0004_chargepoint_last_heartbeat'),
        ('connector', '0003_alter_connector_availability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('reservation_id', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('chargepoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargepoint.chargepoint')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.connector')),
            ],
        ),
    ]
