# Generated by Django 4.2.1 on 2023-06-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='chargepoint',
        ),
    ]
