# Generated by Django 4.1.7 on 2023-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idtag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtag',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
