# Generated by Django 4.2.1 on 2023-06-21 10:27

import chargingprofile.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ocpp.v16.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargingprofile',
            fields=[
                ('chargingprofile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stack_level', models.IntegerField()),
                ('chargingprofile_purpose', models.CharField(choices=[(ocpp.v16.enums.ChargingProfilePurposeType['charge_point_max_profile'], 'ChargePointMaxProfile'), (ocpp.v16.enums.ChargingProfilePurposeType['tx_default_profile'], 'TxDefaultProfile'), (ocpp.v16.enums.ChargingProfilePurposeType['tx_profile'], 'TxProfile')], default=ocpp.v16.enums.ChargingProfilePurposeType['charge_point_max_profile'], max_length=21)),
                ('chargingprofile_kind', models.CharField(choices=[(ocpp.v16.enums.ChargingProfileKindType['absolute'], 'Absolute'), (ocpp.v16.enums.ChargingProfileKindType['recurring'], 'Recurring'), (ocpp.v16.enums.ChargingProfileKindType['relative'], 'Relative')], default=ocpp.v16.enums.ChargingProfileKindType['absolute'], max_length=10)),
                ('recurrency_kind', models.CharField(choices=[(ocpp.v16.enums.RecurrencyKind['daily'], 'Daily'), (ocpp.v16.enums.RecurrencyKind['weekly'], 'Weekly')], default=None, max_length=10, null=True)),
                ('valid_from', models.DateTimeField(default=None, null=True)),
                ('valid_to', models.DateTimeField(default=None, null=True)),
                ('duration', models.IntegerField(default=None, null=True)),
                ('start_schedule', models.DateTimeField(default=None, null=True)),
                ('charging_rate_unit', models.CharField(choices=[(ocpp.v16.enums.ChargingRateUnitType['watts'], 'W'), (ocpp.v16.enums.ChargingRateUnitType['amps'], 'A')], default=ocpp.v16.enums.ChargingRateUnitType['watts'], max_length=1)),
                ('chargingschedule_period', django.contrib.postgres.fields.ArrayField(base_field=chargingprofile.models.ChargingSchedulePeriodField(), size=None)),
                ('min_charging_rate', models.DecimalField(decimal_places=1, default=None, max_digits=5, null=True)),
                ('transaction_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction')),
            ],
        ),
    ]
