# Generated by Django 4.2 on 2023-06-28 08:20

import chargingprofile.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargingprofile',
            fields=[
                ('chargingprofile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stack_level', models.IntegerField()),
                ('chargingprofile_purpose', models.CharField(choices=[('ChargePointMaxProfile', 'ChargePointMaxProfile'), ('TxDefaultProfile', 'TxDefaultProfile'), ('TxProfile', 'TxProfile')], default='ChargePointMaxProfile', max_length=21)),
                ('chargingprofile_kind', models.CharField(choices=[('Absolute', 'Absolute'), ('Recurring', 'Recurring'), ('Relative', 'Relative')], default='Absolute', max_length=10)),
                ('recurrency_kind', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], default=None, max_length=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True)),
                ('duration', models.IntegerField(blank=True, default=None, null=True)),
                ('start_schedule', models.DateTimeField(blank=True, default=None, null=True)),
                ('charging_rate_unit', models.CharField(choices=[('W', 'W'), ('A', 'A')], default='W', max_length=1)),
                ('chargingschedule_period', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[chargingprofile.models.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'limit': {'default': 0, 'example': 'Nom', 'title': 'Nom', 'type': 'number'}, 'number_phases': {'default': 1, 'example': 'Nom', 'title': 'Nom', 'type': 'integer'}, 'startPeriod': {'default': '', 'example': 'Name', 'title': 'Name', 'type': 'string'}}, 'required': ['startPeriod', 'limit', 'number_phases'], 'type': 'object'})]), size=None)),
                ('min_charging_rate', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True)),
                ('transaction_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction')),
            ],
        ),
    ]
