# Generated by Django 4.2 on 2023-07-31 21:01

import chargingprofile.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingprofile',
            name='chargingschedule_period',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[chargingprofile.models.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'limit': {'default': 0, 'example': 'Nom', 'title': 'Nom', 'type': 'number'}, 'number_phases': {'default': 1, 'example': 'Nom', 'title': 'Nom', 'type': 'integer'}, 'startPeriod': {'default': '', 'example': 'Name', 'title': 'Name', 'type': 'integer'}}, 'required': ['startPeriod', 'limit', 'number_phases'], 'type': 'object'})]), size=None),
        ),
    ]
