# Generated by Django 4.2 on 2023-07-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statusnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(choices=[('ConnectorLockFailure', 'ConnectorLockFailure'), ('EVCommunicationError', 'EVCommunicationError'), ('GroundFailure', 'GroundFailure'), ('HighTemperature', 'HighTemperature'), ('InternalError', 'InternalError'), ('LocalListConflict', 'LocalListConflict'), ('NoError', 'NoError'), ('OtherError', 'OtherError'), ('OverCurrentFailure', 'OverCurrentFailure'), ('OverVoltage', 'OverVoltage'), ('PowerMeterFailure', 'PowerMeterFailure'), ('PowerSwitchFailure', 'PowerSwitchFailure'), ('ReaderFailure', 'ReaderFailure'), ('ResetFailure', 'ResetFailure'), ('UnderVoltage', 'UnderVoltage'), ('WeakSignal', 'WeakSignal')], max_length=50)),
                ('info', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Preparing', 'Preparing'), ('Charging', 'Charging'), ('SuspendedEVSE', 'SuspendedEVSE'), ('SuspendedEV', 'SuspendedEV'), ('Finishing', 'Finishing'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('vendor_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vendor_error_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.connector')),
            ],
        ),
    ]
