# Generated by Django 4.2 on 2023-07-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusnotification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusnotification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
