# Generated by Django 4.2 on 2023-08-01 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
        ('chargepoint', '0003_chargepoint_location'),
        ('statusnotification', '0002_alter_statusnotification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusnotification',
            name='chargepoint',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chargepoint.chargepoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statusnotification',
            name='connector',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.connector'),
        ),
    ]
