# Generated by Django 4.2 on 2023-08-02 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statusnotification', '0003_statusnotification_chargepoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusnotification',
            name='id',
        ),
        migrations.AddField(
            model_name='statusnotification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
