# Generated by Django 4.2 on 2023-06-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idtag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_transaction_timestamp', models.DateTimeField()),
                ('stop_transaction_timestamp', models.DateTimeField(null=True)),
                ('wh_meter_start', models.IntegerField()),
                ('wh_meter_stop', models.IntegerField(null=True)),
                ('wh_meter_last', models.IntegerField()),
                ('reason_stopped', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished'), ('Unauthorized', 'Unauthorized')], default='Started', max_length=15)),
                ('id_tag', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idtag.idtag')),
            ],
        ),
    ]
