# Generated by Django 4.1.7 on 2023-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('start_transaction_timestamp', models.DateTimeField()),
                ('stop_transaction_timestamp', models.DateTimeField()),
                ('wh_meter_start', models.IntegerField()),
                ('wh_meter_stop', models.IntegerField()),
            ],
        ),
    ]
