# Generated by Django 4.1.7 on 2023-05-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_tag',
            field=models.CharField(default='asdaf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason_stopped',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stop_transaction_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wh_meter_stop',
            field=models.IntegerField(null=True),
        ),
    ]
