# Generated by Django 4.1.7 on 2023-05-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtag', '0002_alter_idtag_expiry_date'),
        ('transaction', '0002_remove_transaction_id_transaction_id_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idtag.idtag'),
        ),
    ]
