# Generated by Django 4.2.1 on 2023-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_id_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_active',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished'), ('Unauthorized', 'Unauthorized')], default='Started', max_length=15),
        ),
    ]
