# Generated by Django 4.2.1 on 2023-06-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtag', '0002_alter_idtag_expiry_date'),
        ('transaction', '0004_remove_transaction_is_active_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wh_meter_last',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idtag.idtag'),
        ),
    ]
