# Generated by Django 4.1.7 on 2023-05-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargepoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('connectorid', models.IntegerField()),
                ('availability_status', models.IntegerField(choices=[(1, 'Available'), (2, 'Preparing'), (3, 'Charging'), (4, 'Suspended Evse'), (5, 'Suspended Ev'), (6, 'Finishing'), (7, 'Reserved'), (8, 'Unavailable'), (9, 'Faulted')])),
                ('chargepoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargepoint.chargepoint')),
            ],
        ),
    ]
