# Generated by Django 4.2.1 on 2023-06-21 10:33

from django.db import migrations, models
import django.db.models.deletion
import ocpp.v16.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargepoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('connectorid', models.IntegerField()),
                ('availability_status', models.CharField(choices=[(ocpp.v16.enums.AvailabilityType['inoperative'], 'Inoperative'), (ocpp.v16.enums.AvailabilityType['operative'], 'Operative')], default=ocpp.v16.enums.AvailabilityType['operative'], max_length=11)),
                ('connector_status', models.CharField(choices=[(ocpp.v16.enums.ChargePointStatus['available'], 'Available'), (ocpp.v16.enums.ChargePointStatus['preparing'], 'Preparing'), (ocpp.v16.enums.ChargePointStatus['charging'], 'Charging'), (ocpp.v16.enums.ChargePointStatus['suspended_evse'], 'SuspendedEVSE'), (ocpp.v16.enums.ChargePointStatus['suspended_ev'], 'SuspendedEV'), (ocpp.v16.enums.ChargePointStatus['finishing'], 'Finishing'), (ocpp.v16.enums.ChargePointStatus['reserved'], 'Reserved'), (ocpp.v16.enums.ChargePointStatus['unavailable'], 'Unavailable'), (ocpp.v16.enums.ChargePointStatus['faulted'], 'Faulted')], default=ocpp.v16.enums.ChargePointStatus['available'], max_length=13)),
                ('chargepoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargepoint.chargepoint')),
            ],
        ),
    ]
