# Generated by Django 4.2.1 on 2023-06-20 21:23

from django.db import migrations, models
import ocpp.v16.enums


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_alter_connector_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='connector_status',
            field=models.CharField(choices=[(ocpp.v16.enums.ChargePointStatus['available'], 'Available'), (ocpp.v16.enums.ChargePointStatus['preparing'], 'Preparing'), (ocpp.v16.enums.ChargePointStatus['charging'], 'Charging'), (ocpp.v16.enums.ChargePointStatus['suspended_evse'], 'SuspendedEVSE'), (ocpp.v16.enums.ChargePointStatus['suspended_ev'], 'SuspendedEV'), (ocpp.v16.enums.ChargePointStatus['finishing'], 'Finishing'), (ocpp.v16.enums.ChargePointStatus['reserved'], 'Reserved'), (ocpp.v16.enums.ChargePointStatus['unavailable'], 'Unavailable'), (ocpp.v16.enums.ChargePointStatus['faulted'], 'Faulted')], default=ocpp.v16.enums.ChargePointStatus['available'], max_length=13),
        ),
        migrations.AlterField(
            model_name='connector',
            name='availability_status',
            field=models.CharField(choices=[(ocpp.v16.enums.AvailabilityType['inoperative'], 'Inoperative'), (ocpp.v16.enums.AvailabilityType['operative'], 'Operative')], default=ocpp.v16.enums.AvailabilityType['operative'], max_length=11),
        ),
    ]
